#!/bin/bash

. $(dirname $0)/cardano-utils-common

DEFAULT_MAX_COUNT=20

function showHelp() {
    cat <<EOF
usage: $(basename $0) [-m MAXCOUNT] [-h] BLOCK_ID
  -m  Do not count confirmations after this one. Default value is ${DEFAULT_MAX_COUNT}.
  -n  Print only number.
  -h  Show this help.

Prints count of blocks that based on specified block BLOCK_ID.
EOF
}

MAX_COUNT=$DEFAULT_MAX_COUNT

while getopts 'm:L:nh' c
do
    case $c in
        m) if ! is_number $OPTARG; then
               logError 'Wrong value for option `-m`' >&2
               showHelp >&2;
               exit 1
           fi
           MAX_COUNT=$OPTARG
           ;;
        n) ONLY_NUMBER="yes" ;;
        L) if ! parseLogLevel $OPTARG; then
               logError 'Wrong value for option `-L`' >&2
               showHelp >&2
               exit 1
           fi
           ;;
        h) showHelp; exit 0 ;;
        *) showHelp >&2; exit 1 ;;
    esac
done

shift $((OPTIND-1))
if [ -n "$2" ]; then
    logError "Odd argument specified: \`$2\`" >&2
    showHelp >&2
    exit 1
fi

BLOCK_ID=$1

if [ -z "$BLOCK_ID" ]; then
    logError 'BLOCK_ID is mandatory' >&2
    showHelp >&2
    exit 1
fi

catch COUNT ERR_MSG "curl -sSf $JORMUNGANDR_RESTAPI_URL/v0/block/$BLOCK_ID/next_id?count=$MAX_COUNT | xxd -p -c32 | wc -l"

if [ -n "$ERR_MSG" ]; then
    logError "$ERR_MSG" >&2
    exit 1
fi

if [ -n "$ONLY_NUMBER" ]; then
    printf "%d" $COUNT
else
    echo "Confirmation blocks count: $COUNT"
fi
