#!/bin/bash

trap exit1 TERM
trap exit1_ INT
trap logTotal USR1

DEFAULT_CHECK_INTERVAL=10
DEFAULT_CRITICAL_LAG_IN_SEC=100
DEFAULT_UNBELIVABLE_TIME_WO_BLOCKS_IN_NET=200

START_TIME=$(date +%s)
UPTIME=0
DOWNTIME=0
CHECK_CYCLES_FROM_START=0
TOTAL_BOOTSTRAP_DURATION=0
TOTAL_BOOTSTRAP_COUNT=0
LAST_BOOTSTRAP_DURATION=0

WITH_JOURNALD=0
LOG_LEVEL=3 # 1 - error, 2 - warn, 3 - info, 4 - debug, 5 - trace
CRITICAL_LAG_IN_SEC=$DEFAULT_CRITICAL_LAG_IN_SEC
CHECK_INTERVAL=$DEFAULT_CHECK_INTERVAL
UNBELIVABLE_TIME_WO_BLOCKS_IN_NET=$DEFAULT_UNBELIVABLE_TIME_WO_BLOCKS_IN_NET

function showHelp {
    cat <<EOF
usage: $(basename $0) [-i INTERVAL] [-l LAG] [-w LAG_WO_BLOCK] [-L LOG_LEVEL] [-j] [-h]
  -i  The frequency in seconds at which jormungandr health checks will occure.
      If not specified then $DEFAULT_CHECK_INTERVAL seconds interval will be used.
  -l  Critical lag in seconds. If not defined then default value of $DEFAULT_CRITICAL_LAG_IN_SEC will be used.
  -w  Count of seconds without blocks in the net that can apear. If our node does not receive blocks during
      this interval then it will be restarted. Default value - $DEFAULT_UNBELIVABLE_TIME_WO_BLOCKS_IN_NET.
  -L  Log level: 1 - error; 2 - warn; 3 - info; 4 - debug; 5 - trace
  -j  Prepare messages for journald severity levels
  -h  Show this help.

This scrip checks if jormungandr
EOF
}


function is_number {
  if [[ "$1" =~ ^[[:digit:]]+$ ]]; then
    return 0
  else
    return 1
  fi
}

function displaytime {
  local T=$1
  local D=$((T/60/60/24))
  local H=$((T/60/60%24))
  local M=$((T/60%60))
  local S=$((T%60))
  (( $D > 0 )) && printf '%d days ' $D
  (( $H > 0 )) && printf '%d hours ' $H
  (( $M > 0 )) && printf '%d minutes ' $M
  (( $D > 0 || $H > 0 || $M > 0 )) && printf 'and '
  printf '%d seconds\n' $S
}

function logError {
    if (( LOG_LEVEL >= 1  )); then
        (( WITH_JOURNALD )) && echo -n '<3>'
        echo -e "\e[31m$1\e[0m" >&2
    fi
}

function logWarn {
    if (( LOG_LEVEL >= 2  )); then
        (( WITH_JOURNALD )) && echo -n '<4>'
        echo -e "\e[33m$1\e[0m" >&2
    fi
}

function logNotice {
    if (( LOG_LEVEL >= 3  )); then
        (( WITH_JOURNALD )) && echo -n '<5>'
        echo -e "\e[1m$1\e[0m"
    fi
}

function logInfo {
    if (( LOG_LEVEL >= 3  )); then
        (( WITH_JOURNALD )) && echo -n '<6>'
        echo -e "$1"
    fi
}

function logDebug {
    if (( LOG_LEVEL >= 5  )); then
        (( WITH_JOURNALD )) && echo -n '<7>'
        echo -e "\e[2m$1\e[0m"
    fi
}

function logTrace {
    logDebug $1
}



while getopts 'i:l:L:w:jh' c
do
    case $c in
        i) CHECK_INTERVAL="$OPTARG" ;;
        l) if is_number "$OPTARG"; then
               CRITICAL_LAG_IN_SEC=$OPTARG
           else
               echo 'Wrong value for parameter `-l`'
               showHelp;
               exit 1
           fi;;
        w) if is_number "$OPTARG"; then
               UNBELIVABLE_TIME_WO_BLOCKS_IN_NET=$OPTARG
           else
               echo 'Wrong value for parameter `-w`'
               showHelp;
               exit 1
           fi;;
        L) case "$OPTARG" in
               error) LOG_LEVEL=1;;
               warn) LOG_LEVEL=2;;
               info) LOG_LEVEL=3;;
               debug) LOG_LEVEL=4;;
               trace) LOG_LEVEL=5;;
               *) echo 'Wrong value for parameter `-L`'; showHelp; exit 1;;
           esac;;
        j) WITH_JOURNALD=1;;
        h) showHelp; exit 0 ;;
    esac
done



NOW=$(date +%s)

PREV_state=
PREV_CHECK_DATE=

state=
lastBlockTime=
lastReceivedBlockTime=
uptime=
CHECK_DATE=
CONNECTIONS=


function isCriticalLag {
    local LAST_TIME PREV_TIME LAG MAX_LAG
    LAST_TIME=$1
    PREV_TIME=$2
    MAX_LAG=${3:-$CRITICAL_LAG_IN_SEC}
    if !(is_number $LAST_TIME && is_number $PREV_TIME); then
        logError "Not numeric arguments!!!"
        return 1
    fi
    LAG=$(( LAST_TIME - PREV_TIME ))
    logDebug "LAG=$LAG"
    return $(( LAG < MAX_LAG ))
}

function incrementUptime {
    (( UPTIME += CHECK_INTERVAL ))
}

function incrementDowntime {
    (( DOWNTIME += CHECK_INTERVAL ))
}

function incrementBootstrapDuration {
    (( LAST_BOOTSTRAP_DURATION += CHECK_INTERVAL ))
    (( TOTAL_BOOTSTRAP_DURATION += CHECK_INTERVAL ))
}

function stopJormungandr {
    systemctl stop jormungandr
}

function startJormungandr {
    systemctl start jormungandr
}

function restartJormungandr {
    systemctl restart jormungandr
}

function isBootstrappingState {
    if [ "$1" == "Bootstrapping" ] || [ "$1" == "PreparingBlock0" ]; then
        return 0
    else
        return 1
    fi
}

function isRunningState {
    if [ "$1" == "Running" ]; then
        return 0
    else
        return 1
    fi
}

function readJormungandrState {
    local JSON ERR_MSG
    unset state lastBlockTime lastReceivedBlockTime uptime

    eval "$( (jcli rest v0 node stats get --output-format=json) 2> >(ERR_MSG=$(cat); declare -p ERR_MSG) > >(JSON=$(cat); declare -p JSON) )"

    if [ -n "$ERR_MSG" ]; then logError "$ERR_MSG"; fi
    state=$(echo -n $JSON | jq -r .state)
    if isRunningState $state; then
        lastBlockTime=$(date +%s -d$( echo -n "$JSON" | jq -r .lastBlockTime 2>/dev/null) 2>/dev/null)
        lastReceivedBlockTime=$(date +%s -d$( echo -n "$JSON" | jq -r .lastReceivedBlockTime 2>/dev/null) 2>/dev/null)
        uptime=$(echo -n "$JSON" | jq -r .uptime 2>/dev/null)
    fi
    CONNECTIONS=$(netstat -tnp 2>/dev/null| grep -E 'ESTABLISHED.+jormungandr' | cut -c45-65 | sort | uniq | wc -l)
    CHECK_DATE=$(date +%s)
}

function logTotal {
    if (( UPTIME == 0 && DOWNTIME == 0 )); then
        return
    fi
    local uptime_percent
    if (( DOWNTIME > 0 )); then
        uptime_percent=$(echo "scale=2; ${UPTIME:-0}/${DOWNTIME} " | bc -l)
    elif (( UPTIME > 0 )); then
        uptime_percent="100.00"
    else
        uptime_percent="0"
    fi

    local now=$(date +%s)
    logNotice "Total monitoring duration is $(displaytime $(( now - START_TIME )))"
    logNotice "Total percentage of time during witch the node was RUNNING: $uptime_percent"
    if (( TOTAL_BOOTSTRAP_COUNT > 1 )); then
        logNotice "There were $TOTAL_BOOTSTRAP_COUNT bootstraps with an average duration of each $(displaytime $(( TOTAL_BOOTSTRAP_DURATION / TOTAL_BOOTSTRAP_COUNT )))"
    elif (( TOTAL_BOOTSTRAP_COUNT == 1 )); then
        logNotice "There was 1 bootstrap with duration of $(displaytime $TOTAL_BOOTSTRAP_DURATION)"
    else
        logNotice "There were no bootstraps"
    fi
}

function exit1 {
    logTotal
    exit 1
}

function exit1_ {
    echo
    exit1
}

while :;
do
    readJormungandrState
    logTrace "state                 =$state"
    logTrace "lastBlockTime         =$lastBlockTime"
    logTrace "lastReceivedBlockTime =$lastReceivedBlockTime"
    logTrace "now                   =$CHECK_DATE"
    logTrace "uptime                =$uptime"
    logTrace "CONNECTIONS           =$CONNECTIONS"

    if (( CHECK_CYCLES_FROM_START > 0  && ((CHECK_CYCLES_FROM_START * CHECK_INTERVAL) % 3600 == 0) )); then
        logTotal
    fi

    if [ -z "$state" ]; then
        if [ -z "$PREV_CHECK_DATE" ]; then
            if is_number "$CONNECTIONS"; then
                logError "Jormungandr is started but not responding or something wrong with our script"
            else
                logWarn "Starting jormungandr because it looking stopped."
                stopJormungandr
                startJormungandr
            fi;
        elif isCriticalLag $CHECK_DATE $PREV_CHECK_DATE; then
            logWarn "Starting jormungandr because it not responding last $CRITICAL_LAG_IN_SEC seconds."
            stopJormungandr
            startJormungandr
        fi
    elif isBootstrappingState $state; then
        if ! isBootstrappingState $PREV_state; then
            logInfo "Bootstraping..."
            (( TOTAL_BOOTSTRAP_COUNT++ ))
        fi
        incrementBootstrapDuration
        incrementDowntime
    elif isRunningState $state; then
        if isBootstrappingState $PREV_state; then
            incrementBootstrapDuration
            logInfo "Node bootstraped in $LAST_BOOTSTRAP_DURATION seconds ($(displaytime $LAST_BOOTSTRAP_DURATION))"
        elif ! isRunningState $PREV_state; then
            logInfo "Node is running"
        else
            if isCriticalLag $uptime 0 && isCriticalLag ${lastReceivedBlockTime:-$CHECK_DATE} $lastBlockTime; then
                logWarn "Restarting node because of some block did not received during $CRITICAL_LAG_IN_SEC seconds"
                logInfo "Uptime before restart: $uptime seconds ($(displaytime $uptime))"
                incrementDowntime
                restartJormungandr
            elif isCriticalLag $CHECK_DATE ${lastReceivedBlockTime:-$CHECK_DATE} $UNBELIVABLE_TIME_WO_BLOCKS_IN_NET; then
                logWarn "Restarting node because no one block has been received during last $UNBELIVABLE_TIME_WO_BLOCKS_IN_NET seconds"
                logInfo "Uptime before restart: $uptime seconds ($(displaytime $uptime))"
                incrementDowntime
                restartJormungandr
            else
                incrementUptime
            fi
        fi
        (( LAST_BOOTSTRAP_DURATION = 0 ))
    fi

    PREV_CHECK_DATE=$CHECK_DATE
    PREV_state=$state

    sleep "${CHECK_INTERVAL}s"
    (( CHECK_CYCLES_FROM_START += 1 ))
done
