#!/bin/bash

. "$(dirname "$0")/cardano-utils-common"

# Default value of command which output will be sent to the log
DEFAULT_REPORT_CMD='jcli rest v0 node stats get; echo "\nNeigbors: $(netstat -tnp 2> /dev/null| grep -E ''ESTABLISHED.+jormungandr'' | cut -c45-65 | sort | uniq | wc -l)"'


function showHelp() {
    cat <<EOF
usage: $(basename "$0") [-i INTERVAL] [-a TELEGRAM_ACCESS_TOKEN] [-c CHANNEL_ID] [-n HEADER]
         [-x COMMAND] -h
  -i  Interval  that will be used for regular sending.
      If not specified then send info only once and exit.
  -n  Pool name/label. You can use the ticker of your pool here.
      If defined it will be the first line of every telegram message.
  -a  Bot access token. If not specified then environment variable with name \`TELEGRAM_BOT_AUTH_TOKEN\`
      will be used for authentication. If none specified then telegram output will not be used.
  -c  Telegram channel to which send messages. E.g. \`@CardanoNodesHeartbeat\`. You can specify this option
      several times to send message to several channels.
  -x  Command which output will be sent to the log. This is optional parameter.
      If unspecified then the next comand will be used: \`$DEFAULT_REPORT_CMD\`
  -L  Log level. One of the values \`error\`, \`warn\`, \`info\`, \`debug\`, \`trace\`. Only messages with
      this and stronger severity level will be logged.
  -j  Prepare messages for journald severity levels.
  -h  Show this help.

This scrip sends stats information of the jormungandr node to stdout and the telegram channel via the Telegram Bot.

By default, it is assumed that all time INTERVALs are set in seconds. But you can explicitly specify time units:
\`s\` - seconds, \`m\` - minutes, \`h\` - hours, \`d\` - days, \`w\` - weeks. E.g. \`25s\`, \`15m\`, \`1h\`.
EOF
}


REPORT_CMD=$DEFAULT_REPORT_CMD
declare -a T_CHANNEL_IDS
T_CHANNEL_IDS=()
# Access token for Telegram Bot API
T_AUTH_TOKEN=$TELEGRAM_BOT_AUTH_TOKEN

while getopts 'n:x:i:a:c:L:jh' c
do
    case $c in
        n) POOL_LABEL="$OPTARG" ;;
        x) REPORT_CMD="$OPTARG" ;;
        i) INTERVAL=$(printf "%s" "$OPTARG" | parseInterval)
           if [ -z "$INTERVAL" ] || (( INTERVAL < 0 )); then
               logError 'Wrong value for option `-r`' >&2
               showHelp >&2
               exit 1
           fi
           ;;
        a) T_AUTH_TOKEN="$OPTARG" ;;
        c) T_CHANNEL_IDS[${#T_CHANNEL_IDS[*]}]="$OPTARG" ;;
        L) if ! parseLogLevel "$OPTARG"; then
               logError 'Wrong value for option `-L`' >&2
               showHelp >&2
               exit 1
           fi
           ;;
        j) WITH_JOURNALD=1;;
        h) showHelp; exit 0 ;;
        ?) showHelp >&2; exit 1;;
    esac
done


while :;
do
REPORT=$(/bin/sh -c "$REPORT_CMD")
if (( ${#T_CHANNEL_IDS[*]} > 0 )) && [ -n "$T_AUTH_TOKEN" ]; then
    for channel in "${T_CHANNEL_IDS[@]}"
    do
        echo -e "${POOL_LABEL:+${POOL_LABEL}\n}$REPORT" | \
            postToTelegram "$T_AUTH_TOKEN" "$channel"
    done
fi
echo -e "${POOL_LABEL:+${POOL_LABEL}\n}$REPORT"
if [ -z "$INTERVAL" ]; then
    exit 0
fi
sleep "${INTERVAL}m"
done
