#!/bin/bash

. cardano-utils-common

# Default value of command which output will be sent to the log
DEFAULT_REPORT_CMD='jcli rest v0 node stats get; echo "\nNeigbors: $(netstat -tnp 2> /dev/null| grep -E ''ESTABLISHED.+jormungandr'' | cut -c45-65 | sort | uniq | wc -l)"'


function showHelp() {
    cat <<EOF
usage: $(basename $0) -p -i -a -c -r -h
  -p  Pool name/identifier. You can use the ticker of your pool here.
  -i  Interval in minutes that will be used for regular sending.
      If not specified then send info only once and exit.
  -a  Bot access token. If not specified then environment variable with name \`TELEGRAM_BOT_AUTH_TOKEN\`
      will be used for authentication. If none specified then telegram output will not be used.
  -c  Telegram channel to which send messages. E.g. \`@CardanoNodesHeartbeat\`. If not specified then
      the environment variable \`TELEGRAM_CHANNEL_ID\` will be used.
  -r  Command which output will be sent to the log. This is optional parameter.
      If unspecified then the next comand will be used: \`$DEFAULT_REPORT_CMD\`
  -h  Show this help.

This scrip sends stats information of the jormungandr node to stdout and the telegram channel via the Telegram Bot.
EOF
}


REPORT_CMD=$DEFAULT_REPORT_CMD
CHANNEL_ID="$TELEGRAM_CHANNEL_ID"
# Access token for Telegram Bot API
AUTH_TOKEN=$TELEGRAM_BOT_AUTH_TOKEN

while getopts 'p:r:i:a:c:h' c
do
    case $c in
        p) POOL_ID="$OPTARG" ;;
        r) REPORT_CMD="$OPTARG" ;;
        i) INTERVAL="$OPTARG" ;;
        a) AUTH_TOKEN="$OPTARG" ;;
        c) CHANNEL_ID="$OPTARG" ;;
        h) showHelp; exit 0 ;;
        ?) showHelp >&2; exit 1;;
    esac
done


while :;
do
REPORT=$(/bin/sh -c "$REPORT_CMD")
if [ -n "$CHANNEL_ID" ] && [ -n "$AUTH_TOKEN" ]; then
echo -e "${POOL_ID:+${POOL_ID}\n}$REPORT" | \
postToTelegram "$AUTH_TOKEN" "$CHANNEL_ID"
fi
echo -e "${POOL_ID:+${POOL_ID}\n}$REPORT"
if [ -z $INTERVAL ]; then
    exit 0
fi
sleep "${INTERVAL}m"
done
