#!/bin/bash

. "$(dirname "$0")/cardano-utils-common"


function showHelp() {
    cat <<EOF
usage: $(basename "$0") [-i INTERVAL] [-p POOLID] [-u USERID] [-g GENESISPREF] [-e ENCLAVE] [-D] [-C] [-T] [-B]
      [-L LOG_LEVEL] [-j] [-h]
  -i  Interval that will be used for regular checking.
      If not specified then send info only once and exit.
  -p  Pool id. This argument is mandatory.
  -k  Path to the file with KES private key of the pool. This argument is mandatory.
  -e  Enclave leader id. It is integer number. It is helpfull if node carries leadership of several pools.
      If specified then only slots of this enclave leader will be counted. If not specified then all slots
      will be counted regardles of which enclave it belongs to.
  -D  By default count of slots reported only on epoch change or by \`-c\` option.
      Use this option if you want to report count of slots just on program start.
  -L  Log level. One of the values \`error\`, \`warn\`, \`info\`, \`debug\`, \`trace\`. Only messages with
      this and stronger severity level will be logged.
  -j  Prepare messages for journald severity levels.
  -c  Count of blocks to publish. If this option is specified then only report this count of slots for
      the current epoch.
  -h  Show this help.

This scrip send information about slots count to adastat.net statistics service.

By default, it is assumed that all time INTERVALs are set in seconds. But you can explicitly specify time units:
\`s\` - seconds, \`m\` - minutes, \`h\` - hours, \`d\` - days, \`w\` - weeks. E.g. \`25s\`, \`15m\`, \`1h\`.
EOF
}

while getopts 'i:p:k:e:c:DL:jh' c
do
    case $c in
        i) INTERVAL=$(printf "%s" "$OPTARG" | parseInterval)
           if [ -z "$INTERVAL" ] || (( INTERVAL < 0 )); then
               logError 'Wrong value for option `-r`' >&2
               showHelp >&2
               exit 1
           fi
           ;;
        p) POOL_ID="$OPTARG";;
        k) POOL_KES_PRIVATE_KEY_FILE="$OPTARG";;
        e) if ! is_number "$OPTARG"; then
               logError 'Wrong value for option `-e`' >&2
               showHelp >&2
               exit 1
           fi
           ENCLAVE_LEADER_ID="$OPTARG" ;;
        D) WITH_SLOTS_COUNT_REPORT_ON_START=1;;
        c) if ! is_number "$OPTARG"; then
               logError 'Wrong value for option `-c`' >&2
               showHelp >&2
               exit 1
           fi
           MANUAL_SLOTS_COUNT="$OPTARG";;
        L) if ! parseLogLevel "$OPTARG"; then
               logError 'Wrong value for option `-L`' >&2
               showHelp >&2
               exit 1
           fi
           ;;
        j) WITH_JOURNALD=1;;
        h) showHelp; exit 0 ;;
        ?) showHelp >&2; exit 1;;
    esac
done

if [ -z "$POOL_ID" ]; then
    logError 'Option `-p` is mandatory' >&2
    show_help=yes
fi
if [ -z "$POOL_KES_PRIVATE_KEY_FILE" ]; then
    logError 'Option `-k` is mandatory' >&2
    show_help=yes
fi
if [ -n "$MANUAL_SLOTS_COUNT" ]; then
    if [ -n "$INTERVAL" ]; then
        logError 'Options `-c` and `-i` are mutually exclusive' >&2
        show_help=yes
    fi
    if [ -n "$ENCLAVE_LEADER_ID" ]; then
        logError 'Options `-c` and `-e` are mutually exclusive' >&2
        show_help=yes
    fi
fi
if [ -n "$show_help" ]; then
    showHelp >&2
    exit 1
fi


LAST_REPORTED_EPOCH=
LAST_SLOTS_COUNT_REPORT_TRY_TIME=

function fetchNodeStats {
    local JSON ERR_MSG
    catch JSON ERR_MSG "curl -m 5 -sSf $JORMUNGANDR_RESTAPI_URL/v0/node/stats"
    if [ -n "$ERR_MSG" ]; then
        logError "$ERR_MSG" >&2
        return 1
    fi
    echo -n "$JSON"
}

function getCurrentEpoch {
    # STDIN: node stats json

    jq -r '.lastBlockDate' | cut -d. -f1
}

function fetchLeadersLogs {
    local JSON ERR_MSG

    logDebug "$ENCLAVE_LEADER_ID" >&2
    local ENCLAVE_JSON="true"
    if [ -n "$ENCLAVE_LEADER_ID" ]; then
        ENCLAVE_JSON=$(printf '.enclave_leader_id==%d' "$ENCLAVE_LEADER_ID")
    fi

    local JSON ERR_MSG
    catch JSON ERR_MSG "curl -m 5 -sSf $JORMUNGANDR_RESTAPI_URL/v0/leaders/logs"
    if [ -n "$ERR_MSG" ]; then
        logError "$ERR_MSG" >&2
        return 1
    fi
    logDebug "${ENCLAVE_JSON}" >&2
    if [ -n "$JSON" ]; then
        echo -n "$JSON" | \
            jq -c "[( .[] | select(${ENCLAVE_JSON}) )]"
    fi
}

function filterLeadersLogsByEpoch {
    # STDIN: leaders logs json
    local EPOCH=$1

    jq -c --arg EPOCH "$EPOCH" \
       '[ .[] | select(.scheduled_at_date|startswith($EPOCH+".")) ]'
}

function getSlotsCountForEpoch {
    # STDIN: leaders logs json

    local EPOCH=$1
    jq --arg EPOCH "$EPOCH" \
       '[ .[] | select(.scheduled_at_date|startswith($EPOCH+".")) ] | length'
}

function sendSlotsCountToAdastat {
    local EPOCH=$1
    local SLOTS_COUNT=$2

    local PAYLOAD=$(jq -n -c \
                       --arg EPOCH "$EPOCH" \
                       --arg POOLID "$POOL_ID" \
                       --arg ASSIGNED "$SLOTS_COUNT" \
                       '{pool: $POOLID, epoch: $EPOCH, blocks: $ASSIGNED}'
          )
    local SIGNATURE=$(echo -n "$PAYLOAD" | jcli key sign --secret-key "$POOL_KES_PRIVATE_KEY_FILE")

    logInfo "Sending count of assigned slots to adastat.net"
    logInfo "Request payload: $PAYLOAD"
    logInfo "Signature: $SIGNATURE"

    local RESPONSE=$(echo -n "$PAYLOAD" | curl -sSf \
                                               -m 10 \
                                               -H 'Accept: application/json' \
                                               -H 'Content-Type: application/json' \
                                               -H "Authorization: $SIGNATURE" \
                                               -X POST --data @- \
                                               'https://api.adastat.net/rest/v0/poolblocks.json')
    local RESULT_CODE=$?
    [ -n "$RESPONSE" ] && logInfo "Response: $RESPONSE"
    return $RESULT_CODE
}

function doOnce {
    local nodeStatsJson=$(fetchNodeStats)
    if [ -z "$nodeStatsJson" ]; then
        return 1
    fi
    local epoch=$(echo -n "$nodeStatsJson" | getCurrentEpoch)
    if is_number "$epoch"; then
        if [ -n "$MANUAL_SLOTS_COUNT" ]; then
            sendSlotsCountToAdastat "$epoch" "$MANUAL_SLOTS_COUNT"
            exit 0
        else
            if [ -n "$LAST_REPORTED_EPOCH" ] || [ -n "$WITH_SLOTS_COUNT_REPORT_ON_START" ]; then
                if (( $epoch > ${LAST_REPORTED_EPOCH:-0} )); then
                    local currentTime=$(date +%s)
                    if (( $currentTime > (${LAST_SLOTS_COUNT_REPORT_TRY_TIME:-0} + 300) )); # Try not more than once every 5 minutes
                    then
                        local -i tryCount=0
                        local slotsCount=0
                        while true
                        do
                            (( tryCount++ ))
                            local leadersLogs=$(fetchLeadersLogs | filterLeadersLogsByEpoch "$epoch")
                            local -i slotsCount=$(echo -n "$leadersLogs" | jq -r '. | length')
                            LAST_SLOTS_COUNT_REPORT_TRY_TIME=$(date +%s)
                            if is_number "$slotsCount"; then
                                if (( $slotsCount > 0 )) || (( tryCount >= 6 )); then
                                    sendSlotsCountToAdastat "$epoch" "$slotsCount" \
                                        && LAST_REPORTED_EPOCH="$epoch" \
                                        && break
                                fi
                            fi
                            (( tryCount >= 6 )) && break
                            sleep 10
                        done
                        if (( $epoch != ${LAST_REPORTED_EPOCH:-0} )); then
                            logError "Cannot get count of slots" >&2
                        fi
                    fi
                fi
            else
                # Report onlly when epoch changed. Do not report the state at start time as the leaders logs
                # contain all allocated blocks with sure only at the epoch beginning time.
                LAST_REPORTED_EPOCH=$epoch
            fi
        fi
    else
        logError "Cannot get current epoch number" >&2
    fi
}


doOnce

while [ -n "$INTERVAL" ]
do
    sleep "${INTERVAL}s"
    doOnce
done

exit 0
